AllCops:
  TargetRubyVersion: 2.2
  TargetRailsVersion: 4.2
  Exclude:
    - vagrant/**/*
    - script/*_temp.rb

Rails:
  Enabled: true

HasAndBelongsToMany:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - lib/tasks/*
    - lib/tasks/*/*
    - app/*/concerns/*.rb
    - app/views/*/*.xml.builder
    - app/views/*/*.json.jbuilder
    - app/views/*/*/*.xml.builder
    - app/admin/*

Lint/ScriptPermission:
  Exclude:
    - script/*

Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/EmptyCaseCondition:
  Description: 'Avoid empty condition in case statements.'
  Enabled: false
