AllCops:
  RunRailsCops: true
  Exclude:
    - vagrant/**/*

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false
