default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: SQL_ASCII
  host: <%= ENV["DEV_DB_HOST"] %>
  port: <%= ENV["DEV_DB_PORT"] %>
  username: <%= ENV["DEV_DB_USERNAME"] %>
  password: <%= ENV["DEV_DB_PASSWORD"] %>
  database: <%= ENV["DEV_DB_NAME"] %>

development:
  <<: *default

vagrant:
  <<: *default

test:
  <<: *default
  host: <%= ENV["TEST_DB_HOST"] %>
  username: <%= ENV["TEST_DB_USERNAME"] %>
  password: <%= ENV["TEST_DB_PASSWORD"] %>
  database: <%= ENV["TEST_DB_NAME"] %>

production:
  <<: *default
