chart:
  defaultSeriesType: 'area'
  marginLeft: 60
  width: 950
  backgroundColor: 'transparent'
  style:
    background-image: "url('/assets/charts/watermark_692.png')"
    background-repeat: 'no-repeat'
    background-position: '50% 30%'
title: 'Total Lines'
plotOptions:
  area:
    stacking: 'normal'
series:
  - name: 'Code'
    id: 'code'
  - name: 'Comments'
  - name: 'Blanks'
