title: 'Contributors'
tooltip:
  dateFormat: '%B %Y'
series:
  - name: 'Committers'
    id: 'committers'
  - name: 'Current Month'
    type: 'scatter'
    color: 'rgba(119, 152, 191, 3)'
    marker:
      radius: 4
      symbol: 'circle'
